version: "3"
services:
  api:
    build: .
    container_name: SimpleMusicApi
    ports:
      - 8081:8081
    depends_on:
      - database
  database:
    image: postgres:14-alpine
    container_name: PostgresDatabase
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=music_db






